### ISSUE TITLE
有考虑将平台扩大化到P家吗hhh

### ISSUE THREAD

**Issue by nanimouso** [NiaMori/komori-chiyu-button#1]
强强！
这边是团长gachi古守dd，在考虑能不能得到许可借用你的平台给团长也整一个类似的活hhh不过在这方面的代码基本0经验（平时主要是Python居多，而且学的不是cs，这方面基础很弱），目前的想法有几种：
1. 直接借用你这边的整体框架（会附credit）另外建一个项目，然后更换一下素材；
2. 在这个库里另外建一个branch，然后和1类似，好处是整合度高一些而且毕竟代码是你的hhh；
3. 整合度更高一些的方式，用的是同一个网站，然后p家成员的语音按照tab或者勾选的方式出现，不过这样工作量会变大，而且比较麻烦你 - -

大概是这样，不知道你OK吗？对上面的方案哪一种比较感兴趣？期待回复，谢谢

**Comment by NiaMori** [comment]
@nanimouso

谢谢！这里是古守单推人，本项目的代码可以随意使用没有问题。

但本站有不少古守要素，可定制化程度比较低，在其基础上进行修改的话需要一定的前端知识，可以考虑使用 Github 上其他更易用的按钮站模板。

受精力所限，暂时没有将本站直接扩展到整个 P 家的计划，但很乐意提供帮助与交流经验。

**Comment by whe22** [comment]
OK，多谢，我会研究一下，是很棒的想法！

**Comment by nanimouso** [comment]
OK，多谢，我会研究一下，想法很棒！
